lecture3/hello/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("<str:name>", views.greet, name="greet"),
    path("hilde", views.hilde, name="hilde"),
    path("manu", views.manu, name="manu")
]

lecture3/lecture3/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', include("hello.urls")),
    path('newyear/', include("newyear.urls")),
    path('tasks/', include("tasks.urls"))
]

lecture3/newyear/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index")
   
]

lecture3/tasks/urls.py
from django.urls import path
from . import views

app_name = "tasks"
urlpatterns = [
    path("", views.index, name="index"),
    path("add", views.add, name="add")
]

lecture3/tasks/models.py
from django.db import models

# Create your models here.

lecture3/hello/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def index(request):
    return render(request, "hello/index.html")

def hilde(request):
    return HttpResponse("Hello Hilde")

def manu(request):
    return HttpResponse("Dag Manu")

def greet(request, name):
    return render(request, "hello/greet.html", {
        "name": name.capitalize()
    })

lecture3/newyear/views.py
import datetime
from django.shortcuts import render

# Create your views here.
def index(request):
    now = datetime.datetime.now()
    return render(request, "newyear/index.html", {
        "newyear": now.month ==  1 and now.day == 1
    } )

lecture3/tasks/views.py
from django import forms
from django.shortcuts import render

tasks = ["foo", "bar", "baz"]
# Create your views here.

class NewTaskForm(forms.Form):
    FOR_WHO_CHOICES = [
        ('option1','Ivo'),
        ('option2','Joris'),
        ('option3','Victor'),
        ('option4','Hilde')
    ]
    
    for_who = forms.ChoiceField(
        choices=FOR_WHO_CHOICES,
        widget=forms.RadioSelect,
        label="Voor wie?"
    )
    
    task = forms.CharField(label="Nieuwe taak")
    priority = forms.IntegerField(label="Prioriteit", min_value=1, max_value=5)
    

def index(request):
    return render(request, "tasks/index.html", {
        "tasks": tasks
    })
    
def add(request):
    if request.method == "POST":
        form = NewTaskForm(request.POST)
        if form.is_valid():
            task = form.cleaned_data["task"]
            tasks.append(task)
        else:
            return render(request, "tasks/add.html", {
                "form": form
            })    
            
    return render(request, "tasks/add.html", {
        "form": NewTaskForm()
    })

lecture3/hello/templates/hello/greet.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>greet</title>
</head>
<body>
    <h1 style="color: green;">Dada, {{ name }}</h1>
</body>
</html>

lecture3/hello/templates/hello/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hey!</title>
</head>
<body>
    <h1>Hey World</h1>
</body>
</html>

lecture3/newyear/templates/newyear/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Is it New Year's?</title>
    <link rel="stylesheet" href="{% static 'newyear/styles.css' %}">
</head>
<body>
    {% if newyear %}
        <h1>YES</h1>
    {% else %} 
        <h1>NO</h1>   
    {% endif %}
</body>
</html>

lecture3/tasks/templates/tasks/add.html
{% extends "tasks/layout.html" %}

{% block body %}
    <h2>Voeg een taak toe</h2>
    <form style="width: 1000px;" action="{% url 'tasks:add' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit">
    </form>
{% endblock %}

lecture3/tasks/templates/tasks/index.html
{% extends "tasks/layout.html" %}
   
 {% block body %}  
    <h1>Tasks</h1>
   <ul>
        {% for task in tasks %}
            <li>{{ task }}</li>
        {% endfor %}
    </ul>

    <a href="{% url 'add' %}">Add a new task</a>
{% endblock %}

lecture3/tasks/templates/tasks/layout.html
<!--basis voor alle andere html-pagina's-->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Taken</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
    {% block nav %}
    <ul class="nav nav-tabs">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'tasks:index' %}">Open taken</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'tasks:add' %}">Nieuwe taak toevoegen</a>
        </li>
    </ul>
    {% endblock %}
    {% block body %}

    {% endblock %}
    
</body>
</html>